import type { QuranLanguageCode } from '@/types/quran';

const SAJDAH_LABELS: Record<QuranLanguageCode, string> = {
  ar: 'سجدة',
  en: 'Sajdah',
  sq: 'Sexhde',
  ber: 'Sajda',
  am: 'ስግደት',
  as: 'ছাজদাহ',
  az: 'Səcdə',
  bm: 'Sajida',
  bn: 'সিজদাহ',
  bs: 'Sedžda',
  bg: 'Саджда',
  km: 'សុជូដ',
  zh: '叩拜',
  prs: 'سجده',
  dv: 'ސަޖިދަ',
  nl: 'Sajda',
  fr: 'Prosternation',
  de: 'Niederwerfung',
  gu: 'સજદા',
  ha: 'Sujuda',
  he: 'סג׳דה',
  hi: 'सज्दा',
  id: 'Sujud',
  it: 'Prostrazione',
  ja: 'サジュダ',
  kk: 'Сәжде',
  rw: 'Sijida',
  ko: '사즈다',
  ku: 'Secde',
  ms: 'Sujud',
  ml: 'സജ്ദ',
  mrw: 'Sajdah',
  mr: 'सजदा',
  ne: 'सज्दा',
  om: 'Sujuda',
  ps: 'سجده',
  fa: 'سجده',
  pl: 'Sadżda',
  pt: 'Prostração',
  ro: 'Sajdah',
  ru: 'Саджда',
  sd: 'سجدو',
  si: 'සජ්දා',
  so: 'Sajda',
  es: 'Postración',
  sw: 'Sujudu',
  sv: 'Sujud',
  tl: 'Sajda',
  tg: 'Саҷда',
  ta: 'சஜ்தா',
  te: 'సజ్దా',
  th: 'ซัจญ์ดะฮ์',
  tr: 'Secde',
  uk: 'Суджуд',
  ur: 'سجدہ',
  ug: 'سەجدە',
  uz: 'Sajda',
  vi: 'Sajdah',
  yau: 'Sajada',
  yo: 'Foribale',
};

export function getSajdahLabel(language: QuranLanguageCode | string): string {
  const normalized = language.toLowerCase().split('-')[0] as QuranLanguageCode;
  return SAJDAH_LABELS[normalized] || SAJDAH_LABELS.en;
}
